sudo: required

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t acxmatos/multi-docker-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true acxmatos/multi-docker-client-test npm run test